CREATE TABLE IF NOT EXISTS expressions ( 
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  expression_en TEXT,
  meaning_en TEXT,
  meaning_ar TEXT,
  sentence_en TEXT,
  sentence_ar TEXT);

INSERT INTO expressions (
  expression_en,
  meaning_en,
  meaning_ar,
  sentence_en,
  sentence_ar)
  VALUES
('take over', 'assume control', 'تولي السيطرة', 'She decided to take over the project', 'قررت أن تتولى المشروع'),
('go on', 'continue', 'استمر', 'Please go on with your story', 'يرجى الاستمرار في قصتك'),
('break down', 'malfunction', 'تعطّل', 'My car broke down on the way', 'تعطلت سيارتي في الطريق'),
('carry on', 'continue', 'واصل', 'Carry on with your work', 'استمر في عملك'),
('check out', 'examine', 'تحقق من', 'Check out this new book', 'تحقق من هذا الكتاب الجديد'),
('come across', 'encounter', 'صادف', 'I came across an old friend', 'قابلت صديق قديم'),
('find out', 'discover', 'اكتشف', 'I need to find out more information', 'أحتاج لاكتشاف المزيد من المعلومات'),
('get up', 'rise', 'استيقظ', 'I get up early every day', 'أستيقظ باكرًا كل يوم'),
('give up', 'surrender', 'استسلم', 'Never give up on your dreams', 'لا تستسلم أبدًا لأحلامك'),
('look after', 'take care', 'اعتني', 'She looks after her younger brother', 'تهتم بأخيها الأصغر'),
('look for', 'search', 'بحث', 'I am looking for my keys', 'أبحث عن مفاتيحي'),
('put off', 'delay', 'أخر', 'Don\'t put off your homework', 'لا تؤجل واجبك'),
('run into', 'encounter', 'واجه', 'I ran into my teacher at the store', 'قابلت معلمي في المتجر'),
('set up', 'establish', 'أسس', 'They set up a new company', 'أسسوا شركة جديدة'),
('take off', 'depart', 'أقلع', 'The plane will take off soon', 'الطائرة ستقلع قريبًا'),
('turn down', 'reject', 'رفض', 'He turned down the job offer', 'رفض عرض العمل'),
('work out', 'exercise', 'تمرين', 'I work out at the gym daily', 'أتمرن في الصالة الرياضية يوميًا'),
('catch up', 'reach', 'لحاق', 'I need to catch up on my reading', 'أحتاج إلى اللحاق بالقراءة'),
('fall apart', 'break', 'انهار', 'The old chair fell apart', 'الكرسي القديم انهار'),
('get along', 'cooperate', 'تعاون', 'We get along well', 'نتعاون جيدًا'),
('hang out', 'spend time', 'يقضي وقت', 'We hang out at the park', 'نقضي الوقت في الحديقة'),
('let down', 'disappoint', 'خيب', 'I won\'t let you down', 'لن أخذلك'),
('look into', 'investigate', 'تحقق من', 'I\'ll look into the matter', 'سأحقق في الأمر'),
('make up', 'invent', 'اخترع', 'He made up a funny story', 'اخترع قصة مضحكة'),
('pass away', 'die', 'توفي', 'His grandfather passed away', 'توفي جده'),
('pick up', 'collect', 'التقط', 'I\'ll pick you up at 8 PM', 'سأخذك في الساعة الثامنة مساءً'),
('show up', 'arrive', 'وصل', 'He showed up late', 'وصل متأخرًا'),
('take care', 'attend', 'اهتم', 'Take care of your health', 'اهتم بصحتك'),
('wake up', 'awaken', 'استيقظ', 'Wake up early for the meeting', 'استيقظ باكرًا للاجتماع'),
('write down', 'record', 'دوّن', 'Write down the instructions', 'دوّن التعليمات'),
('add up', 'calculate', 'جمع', 'The numbers add up correctly', 'الأرقام تضيف بشكل صحيح'),
('back up', 'support', 'دعم', 'Back up your arguments with facts', 'دعم حججك بالحقائق'),
('call off', 'cancel', 'ألغى', 'They called off the event', 'ألغوا الحدث'),
('cheer up', 'become happy', 'ابتهج', 'Cheer up, everything will be fine', 'ابتهج، كل شيء سيكون على ما يرام'),
('drop by', 'visit', 'زور', 'Drop by anytime', 'زورنا في أي وقت'),
('fall behind', 'lag', 'تأخر', 'I fell behind in my studies', 'تأخرت في دراستي'),
('get over', 'recover', 'تعافى', 'She got over the flu quickly', 'تعافت من الأنفلونزا بسرعة'),
('go through', 'experience', 'مرّ', 'We went through a lot together', 'مررنا بالكثير معًا'),
('hold on', 'wait', 'انتظر', 'Hold on for a moment', 'انتظر لحظة'),
('look out', 'be careful', 'احترس', 'Look out for the car!', 'احترس من السيارة!'),
('make out', 'discern', 'تميز', 'I can\'t make out the handwriting', 'لا أستطيع تمييز الكتابة اليدوية'),
('point out', 'indicate', 'أشار', 'He pointed out the mistakes', 'أشار إلى الأخطاء'),
('put up with', 'tolerate', 'تحمل', 'I can\'t put up with the noise', 'لا أستطيع تحمل الضجيج'),
('run out', 'deplete', 'نفد', 'We ran out of fuel', 'نفد منا الوقود'),
('take down', 'remove', 'أزال', 'Take down the old posters', 'أزل الملصقات القديمة'),
('turn up', 'appear', 'ظهر', 'He turned up at the party', 'ظهر في الحفلة'),
('bring up', 'mention', 'ذكر', 'She brought up an interesting topic', 'أثارت موضوعًا مثيرًا للاهتمام'),
('catch on', 'understand', 'فهم', 'He quickly caught on to the idea', 'فهم الفكرة بسرعة'),
('drop out', 'withdraw', 'انسحب', 'She dropped out of school', 'انسحبت من المدرسة'),
('act up', 'misbehave', 'أساء التصرف', 'The kids were acting up', 'الأطفال كانوا يتصرفون بشكل سيء'),
('bring about', 'cause', 'تسبب', 'The new policy brought about change', 'السياسة الجديدة أحدثت تغييرًا'),
('call up', 'phone', 'اتصل', 'I\'ll call up my friend', 'سأتصل بصديقي'),
('come up with', 'think of', 'فكّر في', 'She came up with a brilliant idea', 'فكرت في فكرة رائعة'),
('count on', 'rely', 'اعتمد على', 'You can count on me', 'يمكنك الاعتماد علي'),
('cut down', 'reduce', 'قلل', 'We need to cut down on expenses', 'نحتاج إلى خفض النفقات'),
('do over', 'redo', 'أعاد العمل', 'I\'ll do it over', 'سأعيد العمل عليه'),
('drop off', 'deliver', 'أوصل', 'Can you drop off the package?', 'هل يمكنك توصيل الطرد؟'),
('eat out', 'dine', 'تناول الطعام خارج المنزل', 'Let\'s eat out tonight', 'لنخرج للعشاء الليلة'),
('fall for', 'be deceived', 'وقع في الفخ', 'Don\'t fall for scams', 'لا تقع في الفخاخ'),
('figure out', 'solve', 'حل', 'I need to figure out this problem', 'أحتاج إلى حل هذه المشكلة'),
('fill in', 'substitute', 'ملأ', 'Can you fill in for me?', 'هل يمكنك أن تحل محلي؟'),
('get by', 'manage', 'تدبر', 'We can get by with what we have', 'يمكننا التدبر بما لدينا'),
('give in', 'surrender', 'استسلم', 'She finally gave in', 'أخيرًا استسلمت'),
('go after', 'pursue', 'طارد', 'Go after your dreams', 'طارد أحلامك'),
('keep up', 'maintain', 'حافظ على', 'Keep up the good work', 'استمر في العمل الجيد'),
('kick off', 'start', 'بدأ', 'The event kicks off at noon', 'الحدث يبدأ في الظهر'),
('let in', 'allow inside', 'أدخل', 'Please let in the guests', 'من فضلك، أدخل الضيوف'),
('look back', 'reflect', 'تأمل', 'Look back on your achievements', 'تأمل في إنجازاتك'),
('pass out', 'faint', 'فقد الوعي', 'He passed out from exhaustion', 'فقد الوعي بسبب الإرهاق'),
('pay back', 'reimburse', 'سدد الدين', 'I\'ll pay you back tomorrow', 'سأرد لك المال غدًا');