 import 'package:english_phrases/expression_model.dart';

List<Expression> getExpressions() {
    return  [
    Expression(
        id: 1,
        expressionEn: 'take over',
        meaningEn: 'assume control',
        meaningAr: 'تولي السيطرة',
        sentenceEn: 'She decided to take over the project',
        sentenceAr: 'قررت أن تتولى المشروع'),
    Expression(
        id: 2,
        expressionEn: 'go on',
        meaningEn: 'continue',
        meaningAr: 'استمر',
        sentenceEn: 'Please go on with your story',
        sentenceAr: 'يرجى الاستمرار في قصتك'),
    Expression(
        id: 3,
        expressionEn: 'break down',
        meaningEn: 'malfunction',
        meaningAr: 'تعطّل',
        sentenceEn: 'My car broke down on the way',
        sentenceAr: 'تعطلت سيارتي في الطريق'),
    Expression(
        id: 4,
        expressionEn: 'carry on',
        meaningEn: 'continue',
        meaningAr: 'واصل',
        sentenceEn: 'Carry on with your work',
        sentenceAr: 'استمر في عملك'),
     Expression(
        id: 5,
        expressionEn: 'check out',
        meaningEn: 'examine',
        meaningAr: 'تحقق من',
        sentenceEn: 'Check out this new book',
        sentenceAr: 'تحقق من هذا الكتاب الجديد'),
    Expression(
        id: 6,
        expressionEn: 'come across',
        meaningEn: 'encounter',
        meaningAr: 'صادف',
        sentenceEn: 'I came across an old friend',
        sentenceAr: 'قابلت صديق قديم'),
    Expression(
        id: 7,
        expressionEn: 'find out',
        meaningEn: 'discover',
        meaningAr: 'اكتشف',
        sentenceEn: 'I need to find out more information',
        sentenceAr: 'أحتاج لاكتشاف المزيد من المعلومات'),
    Expression(
        id: 8,
        expressionEn: 'get up',
        meaningEn: 'rise',
        meaningAr: 'استيقظ',
        sentenceEn: 'I get up early every day',
        sentenceAr: 'أستيقظ باكرًا كل يوم'),
    Expression(
        id: 9,
        expressionEn: 'give up',
        meaningEn: 'surrender',
        meaningAr: 'استسلم',
        sentenceEn: 'Never give up on your dreams',
        sentenceAr: 'لا تستسلم أبدًا لأحلامك'),
    Expression(
        id: 10,
        expressionEn: 'look after',
        meaningEn: 'take care',
        meaningAr: 'اعتني',
        sentenceEn: 'She looks after her younger brother',
        sentenceAr: 'تهتم بأخيها الأصغر'),
    Expression(
        id: 11,
        expressionEn: 'look for',
        meaningEn: 'search',
        meaningAr: 'بحث',
        sentenceEn: 'I am looking for my keys',
        sentenceAr: 'أبحث عن مفاتيحي'),
    Expression(
        id: 12,
        expressionEn: 'put off',
        meaningEn: 'delay',
        meaningAr: 'أخر',
        sentenceEn: 'Don\'t put off your homework',
        sentenceAr: 'لا تؤجل واجبك'),
    Expression(
        id: 13,
        expressionEn: 'run into',
        meaningEn: 'encounter',
        meaningAr: 'واجه',
        sentenceEn: 'I ran into my teacher at the store',
        sentenceAr: 'قابلت معلمي في المتجر'),
    Expression(
        id: 14,
        expressionEn: 'set up',
        meaningEn: 'establish',
        meaningAr: 'أسس',
        sentenceEn: 'They set up a new company',
        sentenceAr: 'أسسوا شركة جديدة'),
    Expression(
        id: 15,
        expressionEn: 'take off',
        meaningEn: 'depart',
        meaningAr: 'أقلع',
        sentenceEn: 'The plane will take off soon',
        sentenceAr: 'الطائرة ستقلع قريبًا'),
     Expression(
        id: 16,
        expressionEn: 'turn down',
        meaningEn: 'reject',
        meaningAr: 'رفض',
        sentenceEn: 'He turned down the job offer',
        sentenceAr: 'رفض عرض العمل'),
    Expression(
        id: 17,
        expressionEn: 'work out',
        meaningEn: 'exercise',
        meaningAr: 'تمرين',
        sentenceEn: 'I work out at the gym daily',
        sentenceAr: 'أتمرن في الصالة الرياضية يوميًا'),
     Expression(
        id: 18,
        expressionEn: 'catch up',
        meaningEn: 'reach',
        meaningAr: 'لحاق',
        sentenceEn: 'I need to catch up on my reading',
        sentenceAr: 'أحتاج إلى اللحاق بالقراءة'),
     Expression(
        id: 19,
        expressionEn: 'fall apart',
        meaningEn: 'break',
        meaningAr: 'انهار',
        sentenceEn: 'The old chair fell apart',
        sentenceAr: 'الكرسي القديم انهار'),
    Expression(
        id: 20,
        expressionEn: 'get along',
        meaningEn: 'cooperate',
        meaningAr: 'تعاون',
        sentenceEn: 'We get along well',
        sentenceAr: 'نتعاون جيدًا'),
     Expression(
        id: 21,
        expressionEn: 'hang out',
        meaningEn: 'spend time',
        meaningAr: 'يقضي وقت',
        sentenceEn: 'We hang out at the park',
        sentenceAr: 'نقضي الوقت في الحديقة'),
      Expression(
        id: 22,
        expressionEn: 'let down',
        meaningEn: 'disappoint',
        meaningAr: 'خيب',
        sentenceEn: 'I won\'t let you down',
        sentenceAr: 'لن أخذلك'),
    Expression(
        id: 23,
        expressionEn: 'look into',
        meaningEn: 'investigate',
        meaningAr: 'تحقق من',
        sentenceEn: 'I\'ll look into the matter',
        sentenceAr: 'سأحقق في الأمر'),
      Expression(
        id: 24,
        expressionEn: 'make up',
        meaningEn: 'invent',
        meaningAr: 'اخترع',
        sentenceEn: 'He made up a funny story',
        sentenceAr: 'اخترع قصة مضحكة'),
    Expression(
        id: 25,
        expressionEn: 'pass away',
        meaningEn: 'die',
        meaningAr: 'توفي',
        sentenceEn: 'His grandfather passed away',
        sentenceAr: 'توفي جده'),
      Expression(
        id: 26,
        expressionEn: 'pick up',
        meaningEn: 'collect',
        meaningAr: 'التقط',
        sentenceEn: 'I\'ll pick you up at 8 PM',
        sentenceAr: 'سأخذك في الساعة الثامنة مساءً'),
     Expression(
        id: 27,
        expressionEn: 'show up',
        meaningEn: 'arrive',
        meaningAr: 'وصل',
        sentenceEn: 'He showed up late',
        sentenceAr: 'وصل متأخرًا'),
      Expression(
        id: 28,
        expressionEn: 'take care',
        meaningEn: 'attend',
        meaningAr: 'اهتم',
        sentenceEn: 'Take care of your health',
        sentenceAr: 'اهتم بصحتك'),
    Expression(
        id: 29,
        expressionEn: 'wake up',
        meaningEn: 'awaken',
        meaningAr: 'استيقظ',
        sentenceEn: 'Wake up early for the meeting',
        sentenceAr: 'استيقظ باكرًا للاجتماع'),
    Expression(
        id: 30,
        expressionEn: 'write down',
        meaningEn: 'record',
        meaningAr: 'دوّن',
        sentenceEn: 'Write down the instructions',
        sentenceAr: 'دوّن التعليمات'),
    Expression(
        id: 31,
        expressionEn: 'add up',
        meaningEn: 'calculate',
        meaningAr: 'جمع',
        sentenceEn: 'The numbers add up correctly',
        sentenceAr: 'الأرقام تضيف بشكل صحيح'),
    Expression(
        id: 32,
        expressionEn: 'back up',
        meaningEn: 'support',
        meaningAr: 'دعم',
        sentenceEn: 'Back up your arguments with facts',
        sentenceAr: 'دعم حججك بالحقائق'),
    Expression(
        id: 33,
        expressionEn: 'call off',
        meaningEn: 'cancel',
        meaningAr: 'ألغى',
        sentenceEn: 'They called off the event',
        sentenceAr: 'ألغوا الحدث'),
    Expression(
        id: 34,
        expressionEn: 'cheer up',
        meaningEn: 'become happy',
        meaningAr: 'ابتهج',
        sentenceEn: 'Cheer up, everything will be fine',
        sentenceAr: 'ابتهج، كل شيء سيكون على ما يرام'),
    Expression(
        id: 35,
        expressionEn: 'drop by',
        meaningEn: 'visit',
        meaningAr: 'زور',
        sentenceEn: 'Drop by anytime',
        sentenceAr: 'زورنا في أي وقت'),
     Expression(
        id: 36,
        expressionEn: 'fall behind',
        meaningEn: 'lag',
        meaningAr: 'تأخر',
        sentenceEn: 'I fell behind in my studies',
        sentenceAr: 'تأخرت في دراستي'),
    Expression(
        id: 37,
        expressionEn: 'get over',
        meaningEn: 'recover',
        meaningAr: 'تعافى',
        sentenceEn: 'She got over the flu quickly',
        sentenceAr: 'تعافت من الأنفلونزا بسرعة'),
    Expression(
        id: 38,
        expressionEn: 'go through',
        meaningEn: 'experience',
        meaningAr: 'مرّ',
        sentenceEn: 'We went through a lot together',
        sentenceAr: 'مررنا بالكثير معًا'),
     Expression(
        id: 39,
        expressionEn: 'hold on',
        meaningEn: 'wait',
        meaningAr: 'انتظر',
        sentenceEn: 'Hold on for a moment',
        sentenceAr: 'انتظر لحظة'),
     Expression(
        id: 40,
        expressionEn: 'look out',
        meaningEn: 'be careful',
        meaningAr: 'احترس',
        sentenceEn: 'Look out for the car!',
        sentenceAr: 'احترس من السيارة!'),
    Expression(
        id: 41,
        expressionEn: 'make out',
        meaningEn: 'discern',
        meaningAr: 'تميز',
        sentenceEn: 'I can\'t make out the handwriting',
        sentenceAr: 'لا أستطيع تمييز الكتابة اليدوية'),
    Expression(
        id: 42,
        expressionEn: 'point out',
        meaningEn: 'indicate',
        meaningAr: 'أشار',
        sentenceEn: 'He pointed out the mistakes',
        sentenceAr: 'أشار إلى الأخطاء'),
    Expression(
        id: 43,
        expressionEn: 'put up with',
        meaningEn: 'tolerate',
        meaningAr: 'تحمل',
        sentenceEn: 'I can\'t put up with the noise',
        sentenceAr: 'لا أستطيع تحمل الضجيج'),
    Expression(
        id: 44,
        expressionEn: 'run out',
        meaningEn: 'deplete',
        meaningAr: 'نفد',
        sentenceEn: 'We ran out of fuel',
        sentenceAr: 'نفد منا الوقود'),
      Expression(
        id: 45,
        expressionEn: 'take down',
        meaningEn: 'remove',
        meaningAr: 'أزال',
        sentenceEn: 'Take down the old posters',
        sentenceAr: 'أزل الملصقات القديمة'),
    Expression(
        id: 46,
        expressionEn: 'turn up',
        meaningEn: 'appear',
        meaningAr: 'ظهر',
        sentenceEn: 'He turned up at the party',
        sentenceAr: 'ظهر في الحفلة'),
     Expression(
        id: 47,
        expressionEn: 'bring up',
        meaningEn: 'mention',
        meaningAr: 'ذكر',
        sentenceEn: 'She brought up an interesting topic',
        sentenceAr: 'أثارت موضوعًا مثيرًا للاهتمام'),
    Expression(
        id: 48,
        expressionEn: 'catch on',
        meaningEn: 'understand',
        meaningAr: 'فهم',
        sentenceEn: 'He quickly caught on to the idea',
        sentenceAr: 'فهم الفكرة بسرعة'),
    Expression(
        id: 49,
        expressionEn: 'drop out',
        meaningEn: 'withdraw',
        meaningAr: 'انسحب',
        sentenceEn: 'She dropped out of school',
        sentenceAr: 'انسحبت من المدرسة'),
      Expression(
        id: 50,
        expressionEn: 'act up',
        meaningEn: 'misbehave',
        meaningAr: 'أساء التصرف',
        sentenceEn: 'The kids were acting up',
        sentenceAr: 'الأطفال كانوا يتصرفون بشكل سيء'),
     Expression(
        id: 51,
        expressionEn: 'bring about',
        meaningEn: 'cause',
        meaningAr: 'تسبب',
        sentenceEn: 'The new policy brought about change',
        sentenceAr: 'السياسة الجديدة أحدثت تغييرًا'),
      Expression(
        id: 52,
        expressionEn: 'call up',
        meaningEn: 'phone',
        meaningAr: 'اتصل',
        sentenceEn: 'I\'ll call up my friend',
        sentenceAr: 'سأتصل بصديقي'),
    Expression(
        id: 53,
        expressionEn: 'come up with',
        meaningEn: 'think of',
        meaningAr: 'فكّر في',
        sentenceEn: 'She came up with a brilliant idea',
        sentenceAr: 'فكرت في فكرة رائعة'),
    Expression(
        id: 54,
        expressionEn: 'count on',
        meaningEn: 'rely',
        meaningAr: 'اعتمد على',
        sentenceEn: 'You can count on me',
        sentenceAr: 'يمكنك الاعتماد علي'),
      Expression(
        id: 55,
        expressionEn: 'cut down',
        meaningEn: 'reduce',
        meaningAr: 'قلل',
        sentenceEn: 'We need to cut down on expenses',
        sentenceAr: 'نحتاج إلى خفض النفقات'),
    Expression(
        id: 56,
        expressionEn: 'do over',
        meaningEn: 'redo',
        meaningAr: 'أعاد العمل',
        sentenceEn: 'I\'ll do it over',
        sentenceAr: 'سأعيد العمل عليه'),
     Expression(
        id: 57,
        expressionEn: 'drop off',
        meaningEn: 'deliver',
        meaningAr: 'أوصل',
        sentenceEn: 'Can you drop off the package?',
        sentenceAr: 'هل يمكنك توصيل الطرد؟'),
    Expression(
        id: 58,
        expressionEn: 'eat out',
        meaningEn: 'dine',
        meaningAr: 'تناول الطعام خارج المنزل',
        sentenceEn: 'Let\'s eat out tonight',
        sentenceAr: 'لنخرج للعشاء الليلة'),
    Expression(
        id: 59,
        expressionEn: 'fall for',
        meaningEn: 'be deceived',
        meaningAr: 'وقع في الفخ',
        sentenceEn: 'Don\'t fall for scams',
        sentenceAr: 'لا تقع في الفخاخ'),
    Expression(
        id: 60,
        expressionEn: 'figure out',
        meaningEn: 'solve',
        meaningAr: 'حل',
        sentenceEn: 'I need to figure out this problem',
        sentenceAr: 'أحتاج إلى حل هذه المشكلة'),
     Expression(
        id: 61,
        expressionEn: 'fill in',
        meaningEn: 'substitute',
        meaningAr: 'ملأ',
        sentenceEn: 'Can you fill in for me?',
        sentenceAr: 'هل يمكنك أن تحل محلي؟'),
    Expression(
        id: 62,
        expressionEn: 'get by',
        meaningEn: 'manage',
        meaningAr: 'تدبر',
        sentenceEn: 'We can get by with what we have',
        sentenceAr: 'يمكننا التدبر بما لدينا'),
    Expression(
        id: 63,
        expressionEn: 'give in',
        meaningEn: 'surrender',
        meaningAr: 'استسلم',
        sentenceEn: 'She finally gave in',
        sentenceAr: 'أخيرًا استسلمت'),
      Expression(
        id: 64,
        expressionEn: 'go after',
        meaningEn: 'pursue',
        meaningAr: 'طارد',
        sentenceEn: 'Go after your dreams',
        sentenceAr: 'طارد أحلامك'),
    Expression(
        id: 65,
        expressionEn: 'keep up',
        meaningEn: 'maintain',
        meaningAr: 'حافظ على',
        sentenceEn: 'Keep up the good work',
        sentenceAr: 'استمر في العمل الجيد'),
    Expression(
        id: 66,
        expressionEn: 'kick off',
        meaningEn: 'start',
        meaningAr: 'بدأ',
        sentenceEn: 'The event kicks off at noon',
        sentenceAr: 'الحدث يبدأ في الظهر'),
    Expression(
        id: 67,
        expressionEn: 'let in',
        meaningEn: 'allow inside',
        meaningAr: 'أدخل',
        sentenceEn: 'Please let in the guests',
        sentenceAr: 'من فضلك، أدخل الضيوف'),
    Expression(
        id: 68,
        expressionEn: 'look back',
        meaningEn: 'reflect',
        meaningAr: 'تأمل',
        sentenceEn: 'Look back on your achievements',
        sentenceAr: 'تأمل في إنجازاتك'),
    Expression(
        id: 69,
        expressionEn: 'pass out',
        meaningEn: 'faint',
        meaningAr: 'فقد الوعي',
        sentenceEn: 'He passed out from exhaustion',
        sentenceAr: 'فقد الوعي بسبب الإرهاق'),
    Expression(
        id: 70,
        expressionEn: 'pay back',
        meaningEn: 'reimburse',
        meaningAr: 'سدد الدين',
        sentenceEn: 'I\'ll pay you back tomorrow',
        sentenceAr: 'سأرد لك المال غدًا'),
  ];

  }